[package]
name = "trusty-gardener"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "trusty-gardener-backend",
    "trusty-gardener-frontend",
    "trusty-gardener-controller",
    "trusty-gardener-model",
]

[dependencies]
